<?php
include_once($_SERVER["DOCUMENT_ROOT"]."/includes/session.php");

if(isset($_REQUEST["school_id"]) && !empty($_REQUEST["school_id"])){
    $user_school_id = $_REQUEST["school_id"];
    $user_details = getUserDetails($_REQUEST["user_id"]);
}else{

    //set nav_point session
    $_SESSION["nav_point"] = "admission";
}
?>
    <?php if($_SESSION["admin_mode"] == "admission") : ?>
    <form action="<?php echo $url?>/admin/admin/submit.php" method="post" name="admissiondetailsForm">
        <div class="body">
            <div class="message_box no_disp">
                <span class="message">Here is a test message</span>
                <div class="close"><span>&cross;</span></div>
            </div>

            <?php
                $row = fetchData("*","admissiondetails","schoolID=$user_school_id");

                $schoolDetail = getSchoolDetail($user_school_id, true);
            ?>

            <div class="joint">
                <input type="hidden" name="school_id" value="<?php echo $user_school_id?>">
                <label for="school_name">
                    <span class="label_image">
                        <img src="<?php echo $url?>/assets/images/icons/user.png" alt="fullname_logo">
                    </span>
                    <input type="text" name="school_name" id="school_name" class="text_input" placeholder="Name of School" pattern="[a-zA-Z\s.-']{6,}"
                    autocomplete="off" title="Update the name of your school" value="<?php echo $schoolDetail["schoolName"]?>">
                    
                </label>
                <label for="school_email">
                    <span class="label_image">
                        <img src="<?php echo $url?>/assets/images/icons/mail-outline.svg" alt="email_icon">
                    </span>
                    <input type="email" name="school_email" id="school_email" class="text_input" placeholder="School's email address"
                    autocomplete="off" title="Update your school email" value="<?php echo $schoolDetail["email"]?>">
                </label>
                <label for="postal_address">
                    <span class="label_image">
                        <img src="<?php echo $url?>/assets/images/icons/Sign Post.png" alt="postal">
                    </span>
                    <input type="text" name="postal_address" id="postal_address" class="text_input" placeholder="Postal Address*"
                    autocomplete="off" title="Update your postal address. It will be useful in details of the admission form"
                    value="<?php echo $schoolDetail["postalAddress"]?>">
                </label>
            </div>
            <div class="joint">
                <label for="head_name">
                    <span class="label_image">
                        <img src="<?php echo $url?>/assets/images/icons/person-outline.svg" alt="head name">
                    </span>
                    <input type="text" name="head_name" id="head_name" class="text_input" placeholder="Name of Head of School*" 
                    autocomplete="off" value="<?php echo $row["headName"] ?>" title="Name of School Head">
                </label>
                <label for="head_title">
                    <span class="label_image">
                        <img src="<?php echo $url?>/assets/images/icons/bag-handle-outline.svg" alt="head title">
                    </span>
                    <input type="text" name="head_title" id="head_title" class="text_input" placeholder="Title of Head*" autocomplete="off" 
                    title="Enter the title of the head provided above. Eg. Head Master or Head Mistress" value="<?php echo $row["titleOfHead"] ?>">
                </label>
            </div>
            
            <div class="joint">
                <label for="admission_year">
                    <span class="label_image" style="align-self: flex-start;">
                        <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="admission year">
                    </span>
                    <div class="flex flex-column" style="flex:1">
                        <input type="text" disabled name="admission_year" id="admission_year" class="text_input" placeholder="Admission" autocomplete="off"
                        title="This is generated automatically, but you can manually input the admission year" maxlength="4" minlength="4" 
                        pattern="[0-9]+" value="<?php echo $row["admissionYear"]?>">
                        <span style="font-size: 11px; color: #999; display: inline-block; text-align: center">Current Admission Year [Generated by system]</span>
                    </div>                    
                </label>
                <label for="academic_year">
                    <span class="label_image" style="align-self: flex-start;">
                        <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="academic year">
                    </span>
                    <div class="flex flex-column" style="flex:1">
                        <input type="text" disabled name="academic_year" id="academic_year" class="text_input" placeholder="Academic Year*" autocomplete="off" 
                        title="Enter the current academic year" maxlength="11" minlength="9" value="<?php echo $row["academicYear"] ?>">
                        <span style="font-size: 11px; color: #999; display: inline-block; text-align: center">Current Academic Year [Generated by system]</span>
                    </div>
                </label>
                <label for="reopening">
                    <span class="label_image" style="align-self: flex-start;">
                        <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="username_logo">
                    </span>
                    <div class="flex flex-column" style="flex:1">
                        <input type="date" name="reopening" id="reopening" class="text_input" placeholder="Reopening Date [eg. <?php echo date("l, d M, Y")?>]*" autocomplete="off" 
                        title="Enter the date of reopening" value="<?php echo $row["reopeningDate"] ?>">
                        <span style="font-size: 11px; color: #999;">Reopening Date for next term</span>
                    </div>
                </label>
            </div>
            
            <label for="admission_head" class="flex flex-column gap-sm sm-xlg-b">
                    <span class="label_title txt-bold">Admission Letter Heading [Optional]</span>
                    <input type="text" name="admission_head" id="admission_head" class="border sp-med txt-al-c" placeholder="Default: Offer of Admission" 
                        title="Provide your custom heading to be displayed on your admission letter" value="<?= $schoolDetail["admissionHead"] ?>">
                </label>
            <label for="admission" class="flex flex-column gap-sm sm-xlg-b">
                <span class="label_title txt-bold">Body of Admission Letter</span>
                <textarea name="admission" id="admission" placeholder="Update the body for your admission letter" 
                class="admin_tinymce" title="Body of admission letter ">
                    <?php 
                        //remove visible escape characters
                        $message = html_entity_decode($schoolDetail["admissionPath"]);
                        $message = str_replace(PHP_EOL, '', $message);
                        echo  $message;
                    ?>
                </textarea>
            </label>
            <label for="description" class="flex flex-column gap-sm sm-xlg-b">
                <span class="label_title txt-bold">Description about your school</span>
                <textarea name="description" id="description" placeholder="A description about your school..." 
                class="admin_tinymce" title="Description of school to be previewed on schools list in main website">
                    <?php 
                        $message = html_entity_decode($schoolDetail["description"]);
                        $message = str_replace(PHP_EOL, '', $message);
                        echo $message 
                    ?>
                </textarea>
            </label>

            <div class="joint flex-wrap">
                <label for="avatar" class="file_label" style="flex:2">
                    <span class="label_title">Update your logo</span>
                    <div class="fore_file_display">
                        <input type="file" name="avatar" id="avatar" accept="image/*">
                        <span class="plus">+</span>
                        <span class="display_file_name">Choose or drag your file here</span>
                    </div>
                </label>
                <label for="display_avatar" class="" style="flex:1">
                    <div id="display_avatar" class="display_image_box">
                        <img src="<?php echo $url."/".$schoolDetail["logoPath"]?>" alt="avatar">
                    </div>
                </label>
            </div>

            <div class="joint">
                <label for="prospectus" class="file_label">
                    <span class="label_title">Please upload your Prospectus (PDF format)</span>
                    <div class="fore_file_display">
                        <input type="file" name="prospectus" id="prospectus" accept=".pdf">
                        <span class="plus">+</span>
                        <span class="display_file_name">Choose or drag your file here</span>
                    </div>
                    <span class="label_title">Current Filename: <a href="<?php 
                        $prospectus = explode("/",$schoolDetail["prospectusPath"]);
                        echo $url."/".$schoolDetail["prospectusPath"];
                    ?>"><?php echo end($prospectus) ?></a></span>
                </label>

                <label for="autoHousePlace" class="checkbox">
                    <input type="checkbox" name="autoHousePlace" id="autoHousePlace" <?php 
                        if($schoolDetail["autoHousePlace"]){
                            echo "checked";
                        } 
                    ?>>
                    <span class="label_title">
                        Automatically Place students into houses<br>
                        This feature is used by the system to place students into houses upon form fill.
                        Not enabling this feature would require you to upload students manually using the default
                        <a href="<?php echo $url?>/admin/admin/files/default files/house_allocation.xlsx">file</a>;
                    </span>
                </label>
            </div>
            <div class="message_box no_disp">
                <span class="message">Here is a test message</span>
                <div class="close"><span>&cross;</span></div>
            </div>
        </div>
        <div class="foot">
            <div class="flex-all-center w-full sm-xlg-b sm-med-t">
                <label for="submit" class="btn sm-unset sp-unset w-full w-full-child wmax-xs">
                    <button type="submit" name="submit" value="admissiondetails" class="primary sp-lg">Save</button>
                </label>
            </div>
            <p>
                @<?php echo date("Y")." ".$_SERVER['HTTP_HOST']?>
            </p>
        </div>
    </form>
    <?php else: ?>
    <section class="section_container">
        <form action="<?= "$url/admin/admin/submit.php" ?>" method="GET" class="w-full sm-med color-dark" method="post" name="recordsForm">
            <div class="body">
                <div class="message_box no_disp">
                    <span class="message">Here is a test message</span>
                    <div class="close"><span>&cross;</span></div>
                </div>
                <?php 
                    $school_result = fetchData("school_result","admissiondetails","schoolID=$user_school_id")["school_result"] ?? "";
                    $result_types = [
                        0 => [
                            "value"=> "",
                            "title"=> "Select a Result Type"
                        ],
                        1 => [
                            "value"=> "wassce",
                            "title"=> "WASSCE Only"
                        ],
                        2 => [
                            "value"=> "ctvet",
                            "title"=> "CTVET Only"
                        ]
                    ]
                ?>
                <label for="school_result" class="flex-column gap-sm">
                    <span class="label_title">Provide the type of result the school uses</span>
                    <select name="school_result" id="school_result">
                        <?php foreach($result_types as $type): ?>
                        <option value="<?= $type["value"] ?>" <?= $school_result === $type["value"] ? "selected" : "" ?>><?= $type["title"] ?></option>
                        <?php endforeach; ?>
                    </select>    
                </label>
                <input type="hidden" name="school_id" value="<?= $user_school_id ?>">
                <label for="submit" class="btn sp-unset sm-auto w-full w-full-child wmax-xs p-lg">
                    <button type="submit" name="submit" id="submit" value="update_result_type" class="teal xs-rnd">Update</button>
                </label>
            </div>
        </form>
    </section>
    <?php 
        $wassce = [
            ["range"=>"80 - 100", "grade"=>"A1"],
            ["range"=>"70 - 79", "grade"=>"B2"],
            ["range"=>"65 - 69", "grade"=>"C3"],
            ["range"=>"60 - 64", "grade"=>"C4"],
            ["range"=>"55 - 59", "grade"=>"C5"],
            ["range"=>"50 - 54", "grade"=>"C6"],
            ["range"=>"45 - 49", "grade"=>"D7"],
            ["range"=>"40 - 44", "grade"=>"E8"],
            ["range"=>"0 - 39", "grade"=>"F9"]
        ];
        $ctvet = [
            ["range"=>"80 - 100", "grade"=>"D"],
            ["range"=>"60 - 79", "grade"=>"C"],
            ["range"=>"40 - 59", "grade"=>"P"],
            ["range"=>"0 - 39", "grade"=>"F"]
        ]
    ?>
    
    <section class="section_container grade_table" id="empty">
        <p class="color-dark sp-xxlg-tp sp-lg-lr">You have not specified the type of results for your school yet</p>
    </section>

    <section class="section_container both grade_table" id="wassce">
        <h3 class="txt-al-c color-dark sm-med-t">Wassce Grade Points</h3>
        <table class="color-dark">
            <thead>
                <td>Grade Range</td>
                <td>Grade</td>
            </thead>

            <tbody>
                <?php foreach($wassce as $grade): ?>
                <tr>
                    <td><?= $grade["range"] ?></td>
                    <td><?= $grade["grade"] ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <section class="section_container both grade_table" id="ctvet">
        <h3 class="txt-al-c color-dark sm-med-t">CTVET Grade Points</h3>
        <table class="color-dark">
            <thead>
                <td>Grade Range</td>
                <td>Grade</td>
            </thead>

            <tbody>
                <?php foreach($ctvet as $grade): ?>
                <tr>
                    <td><?= $grade["range"] ?></td>
                    <td><?= $grade["grade"] ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <script>
        $("select#school_result").change(function(){
            const val = $(this).val() === "" ? "empty" : $(this).val()
            $(".section_container.grade_table").addClass("no_disp")

            if(val != "both")
                $(".section_container#" + val).removeClass("no_disp")
            else
                $(".section_container.both").removeClass("no_disp")
        })

        $(document).ready(function(){
            $("select#school_result").change()
        })

        $("form[name=recordsForm]").submit(function(){
            records = $(this).serialize() + "&submit=" + $(this).find("button[name=submit]").val()
            $.ajax({
                url: "admin/submit.php",
                data: records,
                timeout: 30000,
                beforeSend: function(){
                    messageBoxTimeout("recordsForm","Updating...", "load",0)
                },
                success: function(response){
                    if(response == true){
                        messageBoxTimeout("recordsForm","Update complete", "success")
                    }else{
                        messageBoxTimeout("recordsForm",response,"error",8)
                    }
                },
                error: function(xhr, textStatus){
                    if(textStatus == "timeout"){
                        messageBoxTimeout("recordsForm","Connection was timed out. Please check your network and try again", "error", 0)
                    }
                }
            })
        })
    </script>
    <?php endif; ?>

    <script src="<?php echo $url?>/assets/scripts/form/general.min.js?v=<?php echo time()?>"></script>
    <script src="<?php echo $url?>/admin/assets/scripts/tinymce/jquery.tinymce.min.js"></script>
    <script src="<?php echo $url?>/admin/assets/scripts/tinymce/tinymce.min.js"></script>
    <script src="<?php echo $url?>/admin/assets/scripts/tinymce.min.js?v=<?php echo time()?>"></script>
    <script src="<?php echo $url?>/admin/admin/assets/scripts/admission.min.js?v=<?php echo time()?>"></script>