<form action="<?php echo $url?>/admin/admin/submit.php" method="post" name="admissiondetailsForm" enctype="multipart/form-data">
    <div class="body">
        <div class="message_box no_disp">
            <span class="message">Here is a test message</span>
            <div class="close"><span>&cross;</span></div>
        </div>

        <?php
            $row = fetchData("*","admissiondetails","schoolID=$user_school_id");

            $schoolDetail = getSchoolDetail($user_school_id, true);
        ?>

        <div class="joint">
            <input type="hidden" name="school_id" value="<?php echo $user_school_id?>">
            <label for="school_name">
                <span class="label_image">
                    <img src="<?php echo $url?>/assets/images/icons/user.png" alt="fullname_logo">
                </span>
                <input type="text" name="school_name" id="school_name" class="text_input" placeholder="Name of School" pattern="[a-zA-Z\s.-']{6,}"
                autocomplete="off" title="Update the name of your school" value="<?php echo $schoolDetail["schoolName"]?>">
                
            </label>
            <label for="school_email">
                <span class="label_image">
                    <img src="<?php echo $url?>/assets/images/icons/mail-outline.svg" alt="email_icon">
                </span>
                <input type="email" name="school_email" id="school_email" class="text_input" placeholder="School's email address"
                autocomplete="off" title="Update your school email" value="<?php echo $schoolDetail["email"]?>">
            </label>
            <label for="postal_address">
                <span class="label_image">
                    <img src="<?php echo $url?>/assets/images/icons/Sign Post.png" alt="postal">
                </span>
                <input type="text" name="postal_address" id="postal_address" class="text_input" placeholder="Postal Address*"
                autocomplete="off" title="Update your postal address. It will be useful in details of the admission form"
                value="<?php echo $schoolDetail["postalAddress"]?>">
            </label>
        </div>
        <div class="joint">
            <label for="head_name">
                <span class="label_image">
                    <img src="<?php echo $url?>/assets/images/icons/person-outline.svg" alt="head name">
                </span>
                <input type="text" name="head_name" id="head_name" class="text_input" placeholder="Name of Head of School*" 
                autocomplete="off" value="<?php echo $row["headName"] ?>" title="Name of School Head">
            </label>
            <label for="head_title">
                <span class="label_image">
                    <img src="<?php echo $url?>/assets/images/icons/bag-handle-outline.svg" alt="head title">
                </span>
                <input type="text" name="head_title" id="head_title" class="text_input" placeholder="Title of Head*" autocomplete="off" 
                title="Enter the title of the head provided above. Eg. Head Master or Head Mistress" value="<?php echo $row["titleOfHead"] ?>">
            </label>
        </div>
        
        <div class="joint">
            <label for="admission_year">
                <span class="label_image" style="align-self: flex-start;">
                    <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="admission year">
                </span>
                <div class="flex flex-column" style="flex:1">
                    <input type="text" disabled name="admission_year" id="admission_year" class="text_input" placeholder="Admission" autocomplete="off"
                    title="This is generated automatically, but you can manually input the admission year" maxlength="4" minlength="4" 
                    pattern="[0-9]+" value="<?php echo $row["admissionYear"]?>">
                    <span style="font-size: 11px; color: #999; display: inline-block; text-align: center">Current Admission Year [Generated by system on update]</span>
                </div>                    
            </label>
            <label for="academic_year">
                <span class="label_image" style="align-self: flex-start;">
                    <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="academic year">
                </span>
                <div class="flex flex-column" style="flex:1">
                    <input type="text" disabled name="academic_year" id="academic_year" class="text_input" placeholder="Academic Year*" autocomplete="off" 
                    title="Enter the current academic year" maxlength="11" minlength="9" value="<?php echo $row["academicYear"] ?>">
                    <span style="font-size: 11px; color: #999; display: inline-block; text-align: center">Current Academic Year [Generated by system on update]</span>
                </div>
            </label>
            <label for="reopening">
                <span class="label_image" style="align-self: flex-start;">
                    <img src="<?php echo $url?>/assets/images/icons/calendar-number-outline.svg" alt="username_logo">
                </span>
                <div class="flex flex-column" style="flex:1">
                    <input type="date" name="reopening" id="reopening" class="text_input" placeholder="Reopening Date [eg. <?php echo date("l, d M, Y")?>]*" autocomplete="off" 
                    title="Enter the date of reopening" value="<?php echo $row["reopeningDate"] ?>">
                    <span style="font-size: 11px; color: #999;">Reopening Date for next term</span>
                </div>
            </label>
        </div>
        
        <label for="admission_head" class="flex flex-column gap-sm sm-xlg-b">
                <span class="label_title txt-bold">Admission Letter Heading [Optional]</span>
                <input type="text" name="admission_head" id="admission_head" class="border sp-med txt-al-c" placeholder="Default: Offer of Admission" 
                    title="Provide your custom heading to be displayed on your admission letter" value="<?= $schoolDetail["admissionHead"] ?>">
            </label>
        <label for="admission" class="flex flex-column gap-sm sm-xlg-b">
            <span class="label_title txt-bold">Body of Admission Letter</span>
            <textarea name="admission" id="admission" placeholder="Update the body for your admission letter" 
            class="admin_tinymce" title="Body of admission letter ">
                <?php 
                    //remove visible escape characters
                    $message = html_entity_decode($schoolDetail["admissionPath"]);
                    $message = str_replace(PHP_EOL, '', $message);
                    echo  $message;
                ?>
            </textarea>
        </label>
        <label for="description" class="flex flex-column gap-sm sm-xlg-b">
            <span class="label_title txt-bold">Description about your school</span>
            <textarea name="description" id="description" placeholder="A description about your school..." 
            class="admin_tinymce" title="Description of school to be previewed on schools list in main website">
                <?php 
                    $message = html_entity_decode($schoolDetail["description"]);
                    $message = str_replace(PHP_EOL, '', $message);
                    echo $message 
                ?>
            </textarea>
        </label>

        <div class="joint flex-wrap">
            <label for="avatar" class="file_label" style="flex:2">
                <span class="label_title">Update your logo</span>
                <div class="fore_file_display">
                    <input type="file" name="avatar" id="avatar" accept="image/*">
                    <span class="plus">+</span>
                    <span class="display_file_name">Choose or drag your file here</span>
                </div>
            </label>
            <label for="display_avatar" class="" style="flex:1">
                <div id="display_avatar" class="display_image_box">
                    <img src="<?php echo $url."/".$schoolDetail["logoPath"]?>" alt="avatar">
                </div>
                <input type="hidden" name="old_avatar" value="<?= $schoolDetail["logoPath"] ?>">
            </label>
        </div>

        <?php 
            // prospectus information
            $prospectus_array = $schoolDetail["prospectusPath"];

            if($prospectus_array){
                $prospectus_array = json_decode($prospectus_array, true);
                $prospectus = $prospectus_array["files"];
            }
        ?>

        <label for="multi_prospectus" class="checkbox">
            <input type="checkbox" name="multi_prospectus" id="multi_prospectus" <?= $prospectus_array["type"] == "multiple" ? "checked" : "" ?> />
            <span class="label_title">Separate prospectuses: boarders (male/female) and day students.</span>
        </label>

        <div class="joint <?= $prospectus_array["type"] == "single" ? "no_disp" : "" ?>" id="multi_prospectus_container">
            <label for="male_prospectus" class="file_label">
                <span class="label_title">Prospectus for males (PDF format)</span>
                <div class="fore_file_display">
                    <input type="file" name="male_prospectus" id="male_prospectus" accept=".pdf">
                    <span class="plus">+</span>
                    <span class="display_file_name">Choose or drag your file here</span>
                </div>
                <?php if(!empty($prospectus["male"])): ?>
                <span class="label_title">Current Filename: 
                    <a href="<?= $url.'/'.$prospectus["male"] ?>"><?= getFileName($prospectus["male"]) ?></a>
                </span>
                <?php endif; ?>
            </label>
            <label for="female_prospectus" class="file_label">
                <span class="label_title">Prospectus for females (PDF format)</span>
                <div class="fore_file_display">
                    <input type="file" name="female_prospectus" id="female_prospectus" accept=".pdf">
                    <span class="plus">+</span>
                    <span class="display_file_name">Choose or drag your file here</span>
                </div>
                <?php if(!empty($prospectus["female"])): ?>
                <span class="label_title">Current Filename: 
                    <a href="<?= $url.'/'.$prospectus["female"] ?>"><?= getFileName($prospectus["female"]) ?></a>
                </span>
                <?php endif; ?>
            </label>

            <label for="day_prospectus" class="file_label">
                <span class="label_title">Prospectus for days (PDF format)</span>
                <div class="fore_file_display">
                    <input type="file" name="day_prospectus" id="day_prospectus" accept=".pdf">
                    <span class="plus">+</span>
                    <span class="display_file_name">Choose or drag your file here</span>
                </div>
                <?php if(!empty($prospectus["day"])): ?>
                <span class="label_title">Current Filename: 
                    <a href="<?= $url.'/'.$prospectus["day"] ?>"><?= getFileName($prospectus["day"]) ?></a>
                </span>
                <?php endif; ?>
            </label>
        </div>
        
        <label for="prospectus" id="single_prospectus" class="file_label <?= $prospectus_array["type"] == "multiple" ? "no_disp" : "" ?>">
            <span class="label_title">Please upload your Prospectus (PDF format)</span>
            <div class="fore_file_display">
                <input type="file" name="prospectus" id="prospectus" accept=".pdf">
                <span class="plus">+</span>
                <span class="display_file_name">Choose or drag your file here</span>
            </div>
            <?php if(is_string($prospectus)): ?>
            <span class="label_title">Current Filename: 
                <a href="<?= "$url/$prospectus"?>"><?= getFileName($prospectus) ?></a>
            </span>
            <?php endif; ?>
        </label>
        <input type="hidden" name="old_prospectus" value='<?= $schoolDetail["prospectusPath"] ?>'>
        
        <label for="autoHousePlace" class="checkbox">
            <input type="checkbox" name="autoHousePlace" id="autoHousePlace" <?php 
                if($schoolDetail["autoHousePlace"]){
                    echo "checked";
                } 
            ?>>
            <span class="label_title">
                Automatically Place students into houses<br>
                This feature is used by the system to place students into houses upon form fill.
                Not enabling this feature would require you to upload students manually using the default
                <a href="<?php echo $url?>/admin/admin/files/default files/house_allocation.xlsx">file</a>;
            </span>
        </label>

        <div class="joint">
            <label for="admission_template" class="file_label">
                <span class="label_title">Add a custom admission template here</span>
                <div class="fore_file_display">
                    <input type="file" name="admission_template" id="admission_template" accept=".pdf">
                    <span class="plus">+</span>
                    <span class="display_file_name">Choose or drag your file here</span>
                </div>
                <span class="label_title">
                    <?php if(empty($schoolDetail["admission_template"])): ?>
                        Current Filename: None
                    <?php else: ?>
                    Current Filename: <a href="<?php 
                    $template = explode("/",$schoolDetail["admission_template"]);
                    echo $url."/".$schoolDetail["admission_template"];
                ?>"><?php echo end($template) ?></a><?php endif; ?></span>
                <input type="hidden" name="old_admission_template" value="<?= $schoolDetail["admission_template"] ?>">
            </label>
        </div>
        <div class="message_box no_disp">
            <span class="message">Here is a test message</span>
            <div class="close"><span>&cross;</span></div>
        </div>
    </div>
    <div class="foot">
        <div class="flex-all-center w-full sm-xlg-b sm-med-t">
            <label for="submit" class="btn sm-unset sp-unset w-full w-full-child wmax-xs">
                <button type="submit" name="submit" value="admissiondetails" class="primary sp-lg">Save</button>
            </label>
        </div>
        <p>
            @<?php echo date("Y")." ".$_SERVER['HTTP_HOST']?>
        </p>
    </div>
</form>